export type typeLEVELS = 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED' | 'SPECIALIST';

const BEGINNER: typeLEVELS = 'BEGINNER';
const INTERMEDIATE: typeLEVELS = 'INTERMEDIATE';
const ADVANCED: typeLEVELS = 'ADVANCED';
const SPECIALIST: typeLEVELS = 'SPECIALIST';

const LEVELS = {
  BEGINNER,
  INTERMEDIATE,
  ADVANCED,
  SPECIALIST
}

export default LEVELS;